import os,asyncio,json
from dotenv import load_dotenv
from groq import Groq
from pydantic import BaseModel,Field
from typing import List, Literal

load_dotenv()

class Dataset(BaseModel):
    input:str=Field(description="Input provided by the user")
    ideal_summary:str=Field(description="Summary generated by LLM call")
    category:Literal["code_error", "news_article", "technical_doc", "casual_text", "error_message"]

class DatasetList(BaseModel):
    test_cases: List[Dataset]


class Name:
    def __init__(self):
        self.client = Groq(api_key=os.getenv('api'))

    def dataset_generator(self,num_cases:int=10):
        schema_str=json.dumps(DatasetList.model_json_schema(),indent=2)
        messages=[
            {
                "role":"system",
                "content":f"""
                    You are a test data generator for an AI summarization tool.
                    Generate {num_cases} diverse test cases. Each test case should have:
                    - input: A text snippet (50-200 words)
                    - ideal_summary: A perfect 1-sentence summary (max 20 words)
                    - category: One of [code_error, news_article, technical_doc, casual_text, error_message]

                    Include variety:
                    - 3 code errors
                    - 3 news articles
                    - 2 technical docs
                    - 1 casual text
                    - 1 error message

                    Return a JSON object with a 'test_cases' array containing all test cases.

                    Schema:
                    {schema_str}
                """
            },
            {
                "role":"user",
                "content":f"Generate {num_cases} test cases now."
            }
        ]

        response=self.client.chat.completions.create(
            messages=messages,
            model="llama-3.1-8b-instant",
            response_format={"type":"json_object"}
        )

        raw_json=response.choices[0].message.content
        result=DatasetList.model_validate_json(raw_json)
        return result.test_cases


    def summarize_async(self, text):
        print("[AI] Thinking...")
        
        messages = [
            {"role": "system", "content": "You are a helpful assistant. Provide a concise 1-sentence summary of the provided text."},
            {"role": "user", "content": text}
        ]
        
        try:
            response = self.client.chat.completions.create(
                messages=messages,
                model="llama-3.3-70b-versatile",
                temperature=0.5
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"Error: {e}"


class JudgeScore(BaseModel):
    accuracy: int = Field(description="Score 0-5: Does the summary capture key information from the original text?")
    conciseness: int = Field(description="Score 0-5: Is the summary appropriately brief (1 sentence, max 20 words)?")
    relevance: int = Field(description="Score 0-5: Does the summary focus on what matters, avoiding irrelevant details?")
    total_score: int = Field(description="Sum of accuracy + conciseness + relevance (max 15)")
    max_score: int = Field(description="Maximum possible score, always 15")
    feedback: str = Field(description="Brief explanation (1-2 sentences) of why this score was given")

class Judge:
    def __init__(self):
        self.client = Groq(api_key=os.getenv('api'))
    
    def evaluate(self,user_text,ideal_summary,agent_summary):
        schema_string=json.dumps(JudgeScore.model_json_schema(),indent=2)
        message=[
            {
                "role":"system",
                "content":f"""You are a strict teacher grading an AI's summarization ability.

                You will receive three pieces of information:
                1. ORIGINAL TEXT: What the user highlighted
                2. IDEAL SUMMARY: The "perfect" summary (answer key)
                3. AGENT SUMMARY: What the AI actually produced

                Grade the AGENT SUMMARY on these criteria:

                **Accuracy (0-5):**
                - 5: Perfectly captures all key information
                - 3-4: Captures most key information, minor details missing
                - 1-2: Missing important information or contains errors
                - 0: Completely wrong or irrelevant

                **Conciseness (0-5):**
                - 5: Perfectly brief (1 sentence, under 20 words)
                - 3-4: Slightly too long or could be more concise
                - 1-2: Too verbose or too short
                - 0: Completely inappropriate length

                **Relevance (0-5):**
                - 5: Focuses only on what matters
                - 3-4: Mostly relevant, minor irrelevant details
                - 1-2: Contains significant irrelevant information
                - 0: Completely off-topic

                **Calculations:**
                - total_score = accuracy + conciseness + relevance
                - max_score = 15 (always)

                **Feedback:**
                Provide 1-2 sentences explaining the score. Be specific about what was good or bad.

                Return a JSON object matching this schema:
                {schema_string}"""
            },
            {
                "role":"user",
                "content":f"""ORIGINAL TEXT:
                        {user_text}

                        IDEAL SUMMARY:
                        {ideal_summary}

                        AGENT SUMMARY:
                        {agent_summary}"""
            }
        ]

        response=self.client.chat.completions.create(
            messages=message,
            model="llama-3.1-8b-instant",
            response_format={"type":"json_object"}
        )

        raw_json = response.choices[0].message.content  
        return JudgeScore.model_validate_json(raw_json)


class BenchMark:
    def __init__(self):
        self.client = Groq(api_key=os.getenv('api'))
        self.judge = Judge()
        self.agent = Name()

    def run_benchmark(self, dataset: list) -> dict:
        results = []  
        total_score = 0
        category_scores = {}  
        
        for i, test_case in enumerate(dataset, 1):
            print(f"[{i}/{len(dataset)}] Testing: {test_case.category}")
            
            agent_summary = self.agent.summarize_async(test_case.input)
            
            score = self.judge.evaluate(
                user_text=test_case.input,              
                ideal_summary=test_case.ideal_summary,  
                agent_summary=agent_summary             
            )
            
            result = {
                "category": test_case.category,
                "input": test_case.input[:100] + "...",
                "ideal_summary": test_case.ideal_summary,
                "agent_summary": agent_summary,
                "score": score.total_score,
                "max_score": score.max_score,
                "feedback": score.feedback
            }
            results.append(result)
            
            total_score += score.total_score
            
            if test_case.category not in category_scores:
                category_scores[test_case.category] = []
            category_scores[test_case.category].append(score.total_score)
            
            print(f"   Score: {score.total_score}/{score.max_score} - {score.feedback}")
        
        avg_score = total_score / len(dataset)
        avg_percentage = (avg_score / 15) * 100
        
        category_averages = {}
        for category, scores in category_scores.items():
            category_averages[category] = sum(scores) / len(scores)
        
        return {
            "results": results,
            "avg_score": avg_score,
            "avg_percentage": avg_percentage,
            "category_averages": category_averages
        }


if __name__ == "__main__":
    generator = Name()
    dataset = generator.dataset_generator(num_cases=5)
    
    benchmark = BenchMark()
    results = benchmark.run_benchmark(dataset)
    
    print(f"\nOVERALL: {results['avg_score']:.1f}/15 ({results['avg_percentage']:.1f}%)")
    print(f"\nBY CATEGORY:")
    for cat, avg in results['category_averages'].items():
        print(f"   {cat}: {avg:.1f}/15")